{
    'name': 'Manager Solutions SaaS Manager',
    'version': '18.0.1.0.0',
    'category': 'Website/SaaS',
    'summary': 'Full SaaS platform — plan templates, DB provisioning, subscriptions, owner access',
    'author': 'Manager Solutions',
    'website': 'https://msolutions-eg.com',
    'depends': ['web', 'mail', 'portal', 'website'],
    'data': [
        'security/ms_security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/plan_templates_data.xml',
        'data/mail_templates.xml',
        'data/cron_jobs.xml',
        'views/backend/ms_plan_template_views.xml',
        'views/backend/ms_subscription_views.xml',
        'views/backend/ms_database_views.xml',
        'views/backend/ms_invoice_views.xml',
        'views/backend/ms_dashboard_views.xml',
        'views/backend/menu_items.xml',
        'views/portal/portal_templates.xml',
        'views/website/home_page.xml',
        'views/website/homepage.xml',
        'views/website/pricing_page.xml',
        'views/website/signup_page.xml',
        'views/website/thank_you_page.xml',
        'wizard/ms_provision_wizard_views.xml',
        'wizard/ms_change_plan_views.xml',
        'wizard/ms_copy_modules_wizard_views.xml',
        'wizard/ms_copy_modules_wizard_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'ms_saas_manager/static/src/scss/ms_saas.scss',
            'ms_saas_manager/static/src/js/ms_pricing.js',
            'ms_saas_manager/static/src/js/ms_signup.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
